apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: InternRFC-app-project-user
  template:
    metadata:
      labels:
        app: InternRFC-app-project-user
    spec:
      containers:
      - name: project-user-container
        image: salmak22/projetimage
        ports:
        - containerPort: 3000




