apiVersion: v1
kind: Service
metadata:
  name: project-user-service
spec:
  type: ClusterIP
  selector:
    app: InternRFC-app-project-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000